theme: "hugo-PaperMod"
baseURL: http://skillmigrate.com/
languageCode: en-us
title: Skill Migrate


params:

    defaultTheme: auto
    
    homeInfoParams:
        Title: Mobileholic
        Content: This is my personal blog covering information about skill based migration.\n sjdfalk

    # socialIcons: # optional
    #     - name: "<platform>"
    #         url: "<link>"
    #     - name: "<platform 2>"
    #         url: "<link2>"

