theme: "hugo-PaperMod"
baseURL: "https://aktancy.netlify.app/"
languageCode: en-us
title: Skill Migrate


params:

    defaultTheme: auto
    
    homeInfoParams:
        Title: "Mobileholic"
        Content: >
            This is my personal blog covering skill based migration.
            
            - Low birth rates and population ageing become severer. Sovereignties compete with each other to attract skilled workers. I believe implementing the merit based immigration system will the right to live abroad more accessible.
            
            - This blog focuses on long term settlement in a foreign country, a life style different from [digital nomad](https://en.wikipedia.org/wiki/Digital_nomad). 

    # socialIcons: # optional
    #     - name: "<platform>"
    #         url: "<link>"
    #     - name: "<platform 2>"
    #         url: "<link2>"

